apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: hello-world-deployment-del
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app-del 
  template: 
    metadata: 
      name: hello-world-pod
      labels: 
        app: hello-world-app-del
    spec: 
      containers: 
      - name: hello-world-container 
        image: sganapat3/k8s-by-example-lesson1:latest 
        ports: 
        - containerPort: 8080