apiVersion: v1
kind: Pod
metadata: 
  name: hello-world-pod-del
spec: 
  containers: 
  - name: hello-world-container 
    image: sganapat3/k8s-by-example-lesson1:latest 
    ports: 
    - containerPort: 8080