apiVersion: v1
kind: Service
metadata:
    name: hello-world-app-svc
spec:
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
    selector:
        app: hello-world-app-del
    type: ClusterIP